# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: thatvirtualboy
logo: /assets/favicon.png
image: /assets/banner1.2.jpg
email: thatvirtualboy@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog by Ryan covering all things virtual and other tech bacon
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thatvirtualboy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: thatvirtualboy
github_username:  thatvirtualboy
author:
   name: Ryan Klumph
   twitter: thatvirtualboy
   picture: /assets/profile.jpeg
search: true

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag

# Pagination
paginate: 8  # amount of posts to show per page
paginate_path: /page:num/

# analytics
google_analytics: UA-104130481-1

# comments
disqus:
    shortname: thatvirtualboy

# credit due where credit due
copyright: "© 2020 thatvirtualboy. Photo by [Luke Andrew Scowen](https://www.flickr.com/photos/lukeas09/4129402620). Logo by Christina Klumph at [Powersful Studios.](http://www.powersfulstudios.com)"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#theme: jekyll-theme-basically-basic
remote_theme: "mmistakes/jekyll-theme-basically-basic"

collections:
  releasemenu:
    output: true
    permalink: /:collection/:path/
